spring.application.name=librarian

# MySQL Settings
spring.datasource.url = jdbc:mysql://localhost:3306/librarian_database
spring.datasource.username = libarian_is_cool
spring.datasource.password = libarian_is_cool

# JPA/Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Authorization Settings
app.jwt.secret=uYTqfzsYTmyinfv4U3Wl0VoyRHXvx6Em
app.jwt.expiration=900000
app.jwt.refresh-expiration=604800000

#Demo Admin Credentials
app.bootstrap.admin.username=demo_admin
app.bootstrap.admin.password=1339
app.bootstrap.admin.email=demo_admin@example.com